language: C

install:
  - travis_wait ./setup/travis_install.sh lsst-sims nose pandas pylint
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source eups-setups.sh
  - pip install coveralls
  - setup lsst_sims
  - eups declare -r . charge-transfer-analysis -t current
  - setup charge-transfer-analysis

cache:
  directories:
  - $HOME/miniconda.tarball
  timeout: 600

script:
  - nosetests --with-coverage --cover-package=desc.charge-transfer-analysis
#  - pylint --py3k `find . -name \*.py -print`
#  - pylint --rcfile=.pylintrc `find . -name \*.py -print`

after_success:
  - coveralls
